const API_KEY = 'ec7431cd95fd4bd7597295369dabe181';
const PASSWORD = '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';
const EXAMPLE_URL = 'https://ec7431cd95fd4bd7597295369dabe181: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@demo-store-aaramkhor.myshopify.com/admin/api/2021-10/orders.json';
const SHARED_SECRET = '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'
const HOST_NAME = 'demo-store-aaramkhor.myshopify.com'
const VERSION = '2021-10'

export { API_KEY, PASSWORD, HOST_NAME, VERSION }


const data = {
    id: 4495011315958,
    admin_graphql_api_id: 'gid://shopify/Order/4495011315958',
    app_id: 1354745,
    browser_ip: null,
    buyer_accepts_marketing: true,
    cancel_reason: null,
    cancelled_at: null,
    cart_token: null,
    checkout_id: 29175925276918,
    checkout_token: 'af53240c428ace6fa1eec16f03e04a00',
    client_details: {
        accept_language: null,
        browser_height: null,
        browser_ip: null,
        browser_width: null,
        session_hash: null,
        user_agent: null
    },
    closed_at: '2021-10-24T06:58:15+05:30',
    confirmed: true,
    contact_email: 'tharun4936@gmail.com',
    created_at: '2021-10-24T06:58:03+05:30',
    currency: 'INR',
    current_subtotal_price: '2.00',
    current_subtotal_price_set: {
        shop_money: { amount: '2.00', currency_code: 'INR' },
        presentment_money: { amount: '2.00', currency_code: 'INR' }
    },
    current_total_discounts: '0.00',
    current_total_discounts_set: {
        shop_money: { amount: '0.00', currency_code: 'INR' },
        presentment_money: { amount: '0.00', currency_code: 'INR' }
    },
    current_total_duties_set: null,
    current_total_price: '2.00',
    current_total_price_set: {
        shop_money: { amount: '2.00', currency_code: 'INR' },
        presentment_money: { amount: '2.00', currency_code: 'INR' }
    },
    current_total_tax: '0.00',
    current_total_tax_set: {
        shop_money: { amount: '0.00', currency_code: 'INR' },
        presentment_money: { amount: '0.00', currency_code: 'INR' }
    },
    customer_locale: 'en',
    device_id: null,
    discount_codes: [],
    email: 'tharun4936@gmail.com',
    estimated_taxes: false,
    financial_status: 'paid',
    fulfillment_status: 'fulfilled',
    gateway: 'manual',
    landing_site: null,
    landing_site_ref: null,
    location_id: null,
    name: '#1005',
    note: null,
    note_attributes: [],
    number: 5,
    order_number: 1005,
    order_status_url: 'https://demo-store-aaramkhor.myshopify.com/60660285686/orders/8b7ff68d4ca5520b7e62f3a6384939dc/authenticate?key=dd1c137f5919b530ffc5a3c42c398a59',
    original_total_duties_set: null,
    payment_gateway_names: ['manual'],
    phone: null,
    presentment_currency: 'INR',
    processed_at: '2021-10-24T06:58:03+05:30',
    processing_method: 'manual',
    reference: null,
    referring_site: null,
    source_identifier: null,
    source_name: 'shopify_draft_order',
    source_url: null,
    subtotal_price: '2.00',
    subtotal_price_set: {
        shop_money: { amount: '2.00', currency_code: 'INR' },
        presentment_money: { amount: '2.00', currency_code: 'INR' }
    },
    tags: '',
    tax_lines: [],
    taxes_included: false,
    test: false,
    token: '8b7ff68d4ca5520b7e62f3a6384939dc',
    total_discounts: '0.00',
    total_discounts_set: {
        shop_money: { amount: '0.00', currency_code: 'INR' },
        presentment_money: { amount: '0.00', currency_code: 'INR' }
    },
    total_line_items_price: '2.00',
    total_line_items_price_set: {
        shop_money: { amount: '2.00', currency_code: 'INR' },
        presentment_money: { amount: '2.00', currency_code: 'INR' }
    },
    total_outstanding: '0.00',
    total_price: '2.00',
    total_price_set: {
        shop_money: { amount: '2.00', currency_code: 'INR' },
        presentment_money: { amount: '2.00', currency_code: 'INR' }
    },
    total_price_usd: '0.03',
    total_shipping_price_set: {
        shop_money: { amount: '0.00', currency_code: 'INR' },
        presentment_money: { amount: '0.00', currency_code: 'INR' }
    },
    total_tax: '0.00',
    total_tax_set: {
        shop_money: { amount: '0.00', currency_code: 'INR' },
        presentment_money: { amount: '0.00', currency_code: 'INR' }
    },
    total_tip_received: '0.00',
    total_weight: 0,
    updated_at: '2021-10-24T06:58:15+05:30',
    user_id: 78161543414,
    billing_address: {
        first_name: 'Thanishka',
        address1: 'S1, Aries Block, VGN Avenue, Mogappair East',
        phone: '+919962326281',
        city: 'Chennai',
        zip: '600037',
        province: 'Tamil Nadu',
        country: 'India',
        last_name: 'Ramachandran',
        address2: 'VGN Zodiacville',
        company: 'Thanishka company',
        latitude: 13.075294,
        longitude: 80.1746028,
        name: 'Thanishka Ramachandran',
        country_code: 'IN',
        province_code: 'TN'
    },
    customer: {
        id: 5850116915446,
        email: 'tharun4936@gmail.com',
        accepts_marketing: true,
        created_at: '2021-10-24T06:57:51+05:30',
        updated_at: '2021-10-24T06:58:03+05:30',
        first_name: 'Thanishka',
        last_name: 'Ramachandran',
        orders_count: 1,
        state: 'disabled',
        total_spent: '2.00',
        last_order_id: 4495011315958,
        note: null,
        verified_email: true,
        multipass_identifier: null,
        tax_exempt: true,
        phone: null,
        tags: '',
        last_order_name: '#1005',
        currency: 'INR',
        accepts_marketing_updated_at: '2021-10-24T06:57:51+05:30',
        marketing_opt_in_level: 'single_opt_in',
        admin_graphql_api_id: 'gid://shopify/Customer/5850116915446',
        default_address: {
            id: 7078453444854,
            customer_id: 5850116915446,
            first_name: 'Thanishka',
            last_name: 'Ramachandran',
            company: 'Thanishka company',
            address1: 'S1, Aries Block, VGN Avenue, Mogappair East',
            address2: 'VGN Zodiacville',
            city: 'Chennai',
            province: 'Tamil Nadu',
            country: 'India',
            zip: '600037',
            phone: '+919962326281',
            name: 'Thanishka Ramachandran',
            province_code: 'TN',
            country_code: 'IN',
            country_name: 'India',
            default: true
        }
    },
    discount_applications: [],
    fulfillments: [
        {
            id: 4006942834934,
            admin_graphql_api_id: 'gid://shopify/Fulfillment/4006942834934',
            created_at: '2021-10-24T06:58:14+05:30',
            location_id: 65991508214,
            name: '#1005.1',
            order_id: 4495011315958,
            origin_address: {},
            receipt: {},
            service: 'manual',
            shipment_status: null,
            status: 'success',
            tracking_company: null,
            tracking_number: null,
            tracking_numbers: [],
            tracking_url: null,
            tracking_urls: [],
            updated_at: '2021-10-24T06:58:14+05:30',
            line_items: [Array]
        }
    ],
    line_items: [
        {
            id: 11635171295478,
            admin_graphql_api_id: 'gid://shopify/LineItem/11635171295478',
            destination_location: [Object],
            fulfillable_quantity: 0,
            fulfillment_service: 'manual',
            fulfillment_status: 'fulfilled',
            gift_card: false,
            grams: 0,
            name: 'empty shape',
            origin_location: [Object],
            price: '1.00',
            price_set: [Object],
            product_exists: true,
            product_id: 7342377271542,
            properties: [],
            quantity: 1,
            requires_shipping: true,
            sku: '',
            taxable: true,
            title: 'empty shape',
            total_discount: '0.00',
            total_discount_set: [Object],
            variant_id: 41901583532278,
            variant_inventory_management: null,
            variant_title: '',
            vendor: 'Demo Store aaramkhor',
            tax_lines: [],
            duties: [],
            discount_allocations: []
        },
        {
            id: 11635171328246,
            admin_graphql_api_id: 'gid://shopify/LineItem/11635171328246',
            destination_location: [Object],
            fulfillable_quantity: 0,
            fulfillment_service: 'manual',
            fulfillment_status: 'fulfilled',
            gift_card: false,
            grams: 0,
            name: 'shy dawn',
            origin_location: [Object],
            price: '1.00',
            price_set: [Object],
            product_exists: true,
            product_id: 7342377369846,
            properties: [],
            quantity: 1,
            requires_shipping: true,
            sku: '',
            taxable: true,
            title: 'shy dawn',
            total_discount: '0.00',
            total_discount_set: [Object],
            variant_id: 41901583630582,
            variant_inventory_management: null,
            variant_title: '',
            vendor: 'Demo Store aaramkhor',
            tax_lines: [],
            duties: [],
            discount_allocations: []
        }
    ],
    payment_terms: null,
    refunds: [],
    shipping_address: {
        first_name: 'Thanishka',
        address1: 'S1, Aries Block, VGN Avenue, Mogappair East',
        phone: '+919962326281',
        city: 'Chennai',
        zip: '600037',
        province: 'Tamil Nadu',
        country: 'India',
        last_name: 'Ramachandran',
        address2: 'VGN Zodiacville',
        company: 'Thanishka company',
        latitude: 13.075294,
        longitude: 80.1746028,
        name: 'Thanishka Ramachandran',
        country_code: 'IN',
        province_code: 'TN'
    },
    shipping_lines: []
}
const { contact_email, phone, line_items, shipping_address } = data;
line_items.forEach(item => {


})